actors:
  isaiyiniyan:
    image_url: /images/actors/alice.png
    name: alice
    url: http://sns.example.com/alice
  bob:
    image_url: /images/actors/bob.png
    name: bob
    url: http://sns.example.com/bob
author: Isaiyiniyan
description: இயற்கையின் பேராற்றலால் ..
description_long: இசையோடும் இயற்கையோடும் நாம்
email: info@example.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: examplehashtag
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/TamilNadu
title: இசையினி பண்பலை
url: https://thanithamizhakarathikalanjiyam.github.io/isaiyinifm/
